enhancedModel = {
    "vers": [],
    "name": "Enhanced Cloze 2.1 v2",
    "tags": [],
    "did": 1,
    "usn": -1,
    "flds": [
        {"name": "Content",       "media": [], "sticky": False, "rtl": False, "ord": 0,  "font": "Arial", "size": 20},
        {"name": "Note",          "media": [], "sticky": False, "rtl": False, "ord": 1,  "font": "Arial", "size": 20},
        {"name": "Mnemonics",     "media": [], "sticky": False, "rtl": False, "ord": 2,  "font": "Arial", "size": 20},
        {"name": "Extra",         "media": [], "sticky": False, "rtl": False, "ord": 3,  "font": "Arial", "size": 20},
        {"name": "In-use Clozes", "media": [], "sticky": False, "rtl": False, "ord": 4,  "font": "Arial", "size": 10},
        {"name": "Cloze99",       "media": [], "sticky": False, "rtl": False, "ord": 5,  "font": "Arial", "size": 10},
        {"name": "Cloze1",        "media": [], "sticky": False, "rtl": False, "ord": 6,  "font": "Arial", "size": 10},
        {"name": "Cloze2",        "media": [], "sticky": False, "rtl": False, "ord": 7,  "font": "Arial", "size": 10},
        {"name": "Cloze3",        "media": [], "sticky": False, "rtl": False, "ord": 8,  "font": "Arial", "size": 10},
        {"name": "Cloze4",        "media": [], "sticky": False, "rtl": False, "ord": 9,  "font": "Arial", "size": 10},
        {"name": "Cloze5",        "media": [], "sticky": False, "rtl": False, "ord": 10, "font": "Arial", "size": 10},
        {"name": "Cloze6",        "media": [], "sticky": False, "rtl": False, "ord": 11, "font": "Arial", "size": 10},
        {"name": "Cloze7",        "media": [], "sticky": False, "rtl": False, "ord": 12, "font": "Arial", "size": 10},
        {"name": "Cloze8",        "media": [], "sticky": False, "rtl": False, "ord": 13, "font": "Arial", "size": 10},
        {"name": "Cloze9",        "media": [], "sticky": False, "rtl": False, "ord": 14, "font": "Arial", "size": 10},
        {"name": "Cloze10",       "media": [], "sticky": False, "rtl": False, "ord": 15, "font": "Arial", "size": 10},
        {"name": "Cloze11",       "media": [], "sticky": False, "rtl": False, "ord": 16, "font": "Arial", "size": 10},
        {"name": "Cloze12",       "media": [], "sticky": False, "rtl": False, "ord": 17, "font": "Arial", "size": 10},
        {"name": "Cloze13",       "media": [], "sticky": False, "rtl": False, "ord": 18, "font": "Arial", "size": 10},
        {"name": "Cloze14",       "media": [], "sticky": False, "rtl": False, "ord": 19, "font": "Arial", "size": 10},
        {"name": "Cloze15",       "media": [], "sticky": False, "rtl": False, "ord": 20, "font": "Arial", "size": 10},
        {"name": "Cloze16",       "media": [], "sticky": False, "rtl": False, "ord": 21, "font": "Arial", "size": 10},
        {"name": "Cloze17",       "media": [], "sticky": False, "rtl": False, "ord": 22, "font": "Arial", "size": 10},
        {"name": "Cloze18",       "media": [], "sticky": False, "rtl": False, "ord": 23, "font": "Arial", "size": 10},
        {"name": "Cloze19",       "media": [], "sticky": False, "rtl": False, "ord": 24, "font": "Arial", "size": 10},
        {"name": "Cloze20",       "media": [], "sticky": False, "rtl": False, "ord": 25, "font": "Arial", "size": 10},
        {"name": "data",          "media": [], "sticky": False, "rtl": False, "ord": 26, "font": "Arial", "size": 10},
        {"name": "Cloze21",       "media": [], "sticky": False, "rtl": False, "ord": 27, "font": "Arial", "size": 10},
        {"name": "Cloze22",       "media": [], "sticky": False, "rtl": False, "ord": 28, "font": "Arial", "size": 10},
        {"name": "Cloze23",       "media": [], "sticky": False, "rtl": False, "ord": 29, "font": "Arial", "size": 10},
        {"name": "Cloze24",       "media": [], "sticky": False, "rtl": False, "ord": 30, "font": "Arial", "size": 10},
        {"name": "Cloze25",       "media": [], "sticky": False, "rtl": False, "ord": 31, "font": "Arial", "size": 10},
        {"name": "Cloze26",       "media": [], "sticky": False, "rtl": False, "ord": 32, "font": "Arial", "size": 10},
        {"name": "Cloze27",       "media": [], "sticky": False, "rtl": False, "ord": 33, "font": "Arial", "size": 10},
        {"name": "Cloze28",       "media": [], "sticky": False, "rtl": False, "ord": 34, "font": "Arial", "size": 10},
        {"name": "Cloze29",       "media": [], "sticky": False, "rtl": False, "ord": 35, "font": "Arial", "size": 10},
        {"name": "Cloze30",       "media": [], "sticky": False, "rtl": False, "ord": 36, "font": "Arial", "size": 10},
        {"name": "Cloze31",       "media": [], "sticky": False, "rtl": False, "ord": 37, "font": "Arial", "size": 10},
        {"name": "Cloze32",       "media": [], "sticky": False, "rtl": False, "ord": 38, "font": "Arial", "size": 10},
        {"name": "Cloze33",       "media": [], "sticky": False, "rtl": False, "ord": 39, "font": "Arial", "size": 10},
        {"name": "Cloze34",       "media": [], "sticky": False, "rtl": False, "ord": 40, "font": "Arial", "size": 10},
        {"name": "Cloze35",       "media": [], "sticky": False, "rtl": False, "ord": 41, "font": "Arial", "size": 10},
        {"name": "Cloze36",       "media": [], "sticky": False, "rtl": False, "ord": 42, "font": "Arial", "size": 10},
        {"name": "Cloze37",       "media": [], "sticky": False, "rtl": False, "ord": 43, "font": "Arial", "size": 10},
        {"name": "Cloze38",       "media": [], "sticky": False, "rtl": False, "ord": 44, "font": "Arial", "size": 10},
        {"name": "Cloze39",       "media": [], "sticky": False, "rtl": False, "ord": 45, "font": "Arial", "size": 10},
        {"name": "Cloze40",       "media": [], "sticky": False, "rtl": False, "ord": 46, "font": "Arial", "size": 10},
        {"name": "Cloze41",       "media": [], "sticky": False, "rtl": False, "ord": 47, "font": "Arial", "size": 10},
        {"name": "Cloze42",       "media": [], "sticky": False, "rtl": False, "ord": 48, "font": "Arial", "size": 10},
        {"name": "Cloze43",       "media": [], "sticky": False, "rtl": False, "ord": 49, "font": "Arial", "size": 10},
        {"name": "Cloze44",       "media": [], "sticky": False, "rtl": False, "ord": 50, "font": "Arial", "size": 10},
        {"name": "Cloze45",       "media": [], "sticky": False, "rtl": False, "ord": 51, "font": "Arial", "size": 10},
        {"name": "Cloze46",       "media": [], "sticky": False, "rtl": False, "ord": 52, "font": "Arial", "size": 10},
        {"name": "Cloze47",       "media": [], "sticky": False, "rtl": False, "ord": 53, "font": "Arial", "size": 10},
        {"name": "Cloze48",       "media": [], "sticky": False, "rtl": False, "ord": 54, "font": "Arial", "size": 10},
        {"name": "Cloze49",       "media": [], "sticky": False, "rtl": False, "ord": 55, "font": "Arial", "size": 10},
        {"name": "Cloze50",       "media": [], "sticky": False, "rtl": False, "ord": 56, "font": "Arial", "size": 10},
    ],
    "sortf":0,
    "tmpls": [
            {
            "name": "Enhanced Cloze",
            "qfmt": "",
            "did": None,
            "bafmt": "",
            "afmt": "",
            "ord": 0,
            "bqfmt": ""
            }
        ],
    "mod": 1560146886,
    "latexPost": "\\end{document}",
    "type": 1,
    "id": 0,
    "css": "",
 "latexPre": """\\documentclass[12pt]{article}
\\special{papersize=3in,5in}
\\usepackage[utf8]{inputenc}
\\usepackage{amssymb,amsmath}
\\pagestyle{empty}
\\setlength{\\parindent}{0in}
\\begin{document}
"""}
